// <auto-generated/> Generated by VSIX project wizard
// PkgCmdID.cs
// MUST match PkgCmdID.h

namespace RedisExplorer
{
    static class PkgCmdIDList
    {

        public const uint cmdidRedisExplorer =    0x101;

    };
}